import { CompanyReport } from './types';

export const INITIAL_REPORTS: CompanyReport[] = [
  {
    id: 'ri-happy-demo',
    name: 'Ri Happy Brinquedos',
    sector: 'Varejo / Brinquedos',
    founded: '1988',
    headquarters: 'São Paulo, Brasil',
    overview: 'Líder absoluta no varejo de brinquedos no Brasil. Nasceu com foco em atendimento consultivo e experiência lúdica.',
    history: 'Fundada por Ricardo Sayon e sócios. Em 2012, o fundo Carlyle adquiriu participação majoritária, impulsionando a aquisição da PBKids e expansão digital.',
    structure: 'Executivo (CEO), Diretorias (Comercial, Ops, Mkt, RH), Gerentes Regionais, Gerentes de Loja e Equipes de Vendas.',
    marketPresence: '~196 lojas em todo o Brasil. Forte presença em shoppings e expansão no e-commerce. Marcas: Ri Happy e PBKids.',
    financials: 'Faturamento estimado acima de R$300 milhões/ano. Empresa de capital fechado com forte governança corporativa.',
    culture: 'Foco total na experiência da criança ("Encantamento"). Valoriza atendimento, proatividade e espírito de equipe. Ambiente dinâmico de varejo.',
    salaries: [
      { role: 'Auxiliar de Loja', range: 'R$ 1.7k - 2.4k', avgValue: 2050 },
      { role: 'Vendedor', range: 'R$ 1.8k - 2.8k', avgValue: 2300 },
      { role: 'Gerente de Loja', range: 'R$ 3.4k+', avgValue: 3400 },
      { role: 'Analista Pleno', range: 'R$ 4k - 5.5k', avgValue: 4750 },
    ],
    competitiveness: 'Líder de mercado (Market Share alto). Concorre com marketplaces (Amazon, ML) e lojas de departamento, mas vence na experiência física.',
    interviewTips: [
      'Demonstre paixão por atender famílias e crianças.',
      'Cite exemplos de vendas consultivas e superação de metas.',
      'Mostre resiliência para trabalhar em horários de shopping e datas sazonais (Natal/Dia das Crianças).',
    ],
    sources: ['Glassdoor', 'LinkedIn', 'Institutional Site', 'Retail Reports'],
    generatedAt: new Date().toISOString(),
  },
  {
    id: 'uber-demo',
    name: 'Uber Technologies Inc.',
    sector: 'Tecnologia / Mobilidade',
    founded: '2009',
    headquarters: 'San Francisco, EUA',
    overview: 'Plataforma global que revolucionou a mobilidade urbana e delivery. Opera como um marketplace conectando motoristas/entregadores a usuários.',
    history: 'Fundada como UberCab. Pivotou para serviços diversos (Eats, Freight). IPO em 2019. Tornou-se lucrativa operacionalmente em 2023.',
    structure: 'Matricial e Global. CEO > SVPs (Mobility, Delivery, Tech, Legal). Times organizados por Produto e Geografia.',
    marketPresence: 'Presente em +70 países e +10.000 cidades. Líder global em ride-hailing fora da China.',
    financials: 'Receita global ~US$37B+ (2023). Primeiro ano de lucro operacional. Crescimento sustentado em Delivery e Ads.',
    culture: 'Data-driven, "Go get it", Inovação rápida. Ambiente de alta performance e competitividade técnica.',
    salaries: [
      { role: 'Software Eng. II', range: 'US$ 150k - 200k/ano', avgValue: 175000 },
      { role: 'Senior SWE', range: 'US$ 200k - 350k/ano', avgValue: 275000 },
      { role: 'Product Manager', range: 'US$ 160k - 220k/ano', avgValue: 190000 },
      { role: 'Data Scientist', range: 'US$ 140k - 210k/ano', avgValue: 175000 },
    ],
    competitiveness: 'Compete com Lyft (EUA), 99/Didi (Latam/China), iFood/DoorDash (Delivery). Vantagem na escala global e tecnologia.',
    interviewTips: [
      'Foco em "Ubergeist" (valores culturais).',
      'Prepare-se para System Design e Algoritmos (Tech).',
      'Demonstre capacidade de tomar decisões baseadas em dados (Data-driven).',
      'Tenha exemplos de impacto mensurável (métricas).',
    ],
    sources: ['SEC Filings (10-K)', 'Levels.fyi', 'TechCrunch', 'Uber Investor Relations'],
    generatedAt: new Date().toISOString(),
  },
];
